package com.serhiiromanchuk.mastermeme.presentation.core.utils

import com.serhiiromanchuk.mastermeme.R

//object MemeTemplateProvider {
//    val memesList = listOf(
//        R.drawable.disaster_girl_1,
//        R.drawable.epic_handshake_2,
//        R.drawable.left_exit_12_off_ramp_3,
//        R.drawable.sad_pablo_escobar_4,
//        R.drawable.change_my_mind_5,
//        R.drawable.two_buttons_6,
//        R.drawable.hide_the_pain_harold_7,
//        R.drawable.the_rock_driving_8,
//        R.drawable.grus_plan_9,
//        R.drawable.i_bet_hes_thinking_about_other_women_10,
//        R.drawable.third_world_skeptical_kid_11,
//        R.drawable.eqjd8_12,
//        R.drawable.iacv_13,
//        R.drawable.running_away_balloon_14,
//        R.drawable.zoa8_15,
//        R.drawable.f0mvv_16,
//        R.drawable.w2e5e_17,
//        R.drawable.sz4u_18,
//        R.drawable.u6ylb_19,
//        R.drawable.soh_20,
//        R.drawable.is_this_a_pigeon_21,
//        R.drawable.yz6z4_22,
//        R.drawable.jack_sparrow_being_chased_23,
//        R.drawable.leonardo_dicaprio_cheers_24,
//        R.drawable.op9wy_25,
//        R.drawable.t8r9a_26,
//        R.drawable.vt4i_27,
//        R.drawable.two_buttons_28,
//        R.drawable.bbctk_29,
//        R.drawable.c9dbh_30,
//        R.drawable.clown_applying_makeup_31,
//        R.drawable.eb198_32,
//        R.drawable.byuiy_33,
//        R.drawable.scared_cat_34,
//        R.drawable.i_was_told_there_would_be_35,
//        R.drawable.boardroom_meeting_suggestion_36,
//        R.drawable.p2is_38,
//        R.drawable.rcrc1_39,
//        R.drawable.otri4_40,
//        R.drawable.su9f_41,
//        R.drawable.wxtd1_42,
//        R.drawable.waiting_skeleton_43,
//        R.drawable.jgrgn_44,
//        R.drawable.eyvu_45,
//        R.drawable.ajtl_46,
//        R.drawable.igo27_47,
//        R.drawable.c1hh_48,
//        R.drawable.qx7sw_49,
//        R.drawable.reqtg_50
//    )
//}

data class MemeTemplate(val name: String, val resource: Int)

object MemeTemplateProvider {
    val memesList = listOf(
        MemeTemplate("disaster_girl", R.drawable.disaster_girl_1),
        MemeTemplate("epic_handshake", R.drawable.epic_handshake_2),
        MemeTemplate("left_exit_12_off_ramp", R.drawable.left_exit_12_off_ramp_3),
        MemeTemplate("sad_pablo_escobar", R.drawable.sad_pablo_escobar_4),
        MemeTemplate("change_my_mind", R.drawable.change_my_mind_5),
        MemeTemplate("two_buttons", R.drawable.two_buttons_6),
        MemeTemplate("hide_the_pain_harold", R.drawable.hide_the_pain_harold_7),
        MemeTemplate("the_rock_driving", R.drawable.the_rock_driving_8),
        MemeTemplate("grus_plan", R.drawable.grus_plan_9),
        MemeTemplate("i_bet_hes_thinking_about_other_women", R.drawable.i_bet_hes_thinking_about_other_women_10),
        MemeTemplate("third_world_skeptical_kid", R.drawable.third_world_skeptical_kid_11),
        MemeTemplate("eqjd8", R.drawable.eqjd8_12),
        MemeTemplate("iacv", R.drawable.iacv_13),
        MemeTemplate("running_away_balloon", R.drawable.running_away_balloon_14),
        MemeTemplate("zoa8", R.drawable.zoa8_15),
        MemeTemplate("f0mvv", R.drawable.f0mvv_16),
        MemeTemplate("w2e5e", R.drawable.w2e5e_17),
        MemeTemplate("sz4u", R.drawable.sz4u_18),
        MemeTemplate("u6ylb", R.drawable.u6ylb_19),
        MemeTemplate("soh", R.drawable.soh_20),
        MemeTemplate("is_this_a_pigeon", R.drawable.is_this_a_pigeon_21),
        MemeTemplate("yz6z4", R.drawable.yz6z4_22),
        MemeTemplate("jack_sparrow_being_chased", R.drawable.jack_sparrow_being_chased_23),
        MemeTemplate("leonardo_dicaprio_cheers", R.drawable.leonardo_dicaprio_cheers_24),
        MemeTemplate("op9wy", R.drawable.op9wy_25),
        MemeTemplate("t8r9a", R.drawable.t8r9a_26),
        MemeTemplate("vt4i", R.drawable.vt4i_27),
        MemeTemplate("two_buttons_28", R.drawable.two_buttons_28),
        MemeTemplate("bbctk", R.drawable.bbctk_29),
        MemeTemplate("c9dbh", R.drawable.c9dbh_30),
        MemeTemplate("clown_applying_makeup", R.drawable.clown_applying_makeup_31),
        MemeTemplate("eb198", R.drawable.eb198_32),
        MemeTemplate("byuiy", R.drawable.byuiy_33),
        MemeTemplate("scared_cat", R.drawable.scared_cat_34),
        MemeTemplate("i_was_told_there_would_be", R.drawable.i_was_told_there_would_be_35),
        MemeTemplate("boardroom_meeting_suggestion", R.drawable.boardroom_meeting_suggestion_36),
        MemeTemplate("p2is", R.drawable.p2is_38),
        MemeTemplate("rcrc1", R.drawable.rcrc1_39),
        MemeTemplate("otri4", R.drawable.otri4_40),
        MemeTemplate("su9f", R.drawable.su9f_41),
        MemeTemplate("wxtd1", R.drawable.wxtd1_42),
        MemeTemplate("waiting_skeleton", R.drawable.waiting_skeleton_43),
        MemeTemplate("jgrgn", R.drawable.jgrgn_44),
        MemeTemplate("eyvu", R.drawable.eyvu_45),
        MemeTemplate("ajtl", R.drawable.ajtl_46),
        MemeTemplate("igo27", R.drawable.igo27_47),
        MemeTemplate("c1hh", R.drawable.c1hh_48),
        MemeTemplate("qx7sw", R.drawable.qx7sw_49),
        MemeTemplate("reqtg", R.drawable.reqtg_50)
    )

    fun filterMemesByName(query: String): List<MemeTemplate> {
        return memesList.filter { it.name.contains(query, ignoreCase = true) }
    }
}